#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Set GTK Themes, Icons, Cursor and Fonts

# you can set your icons, themes and cursur via
# dconf editor

# /org/gnome/desktop/interface

